environment: "dev"
catalog: "maven_market_uc"
secret_scope: "scope-maven-market"

# Delta Live Tables Pipeline Settings
dlt:
  pipeline_id: "7b2cf906-43b5-4563-ac2f-0d54fcfda519" # Replace with your DLT Pipeline ID

storage:
  base_path: "abfss://root@stmavenmarket.dfs.core.windows.net"
  checkpoint_base: "abfss://root@stmavenmarket.dfs.core.windows.net/_checkpoints"

sources:
  pos_csv:
    transactions: "/raw/transactions/"
    stores: "/raw/stores/"
    regions: "/raw/regions/"
    calendar: "/raw/calendar/"
    returns: "/raw/returns/"
  mongodb:
    database: "maven_market_db"
    uri_secret_key: "mongodb-connection-uri"
    collections:
      customers: "customers"
      products: "products"
  kafka:
    bootstrap_secret_key: "kafka-bootstrap-servers"
    api_key_secret_key: "kafka-api-key"
    api_secret_secret_key: "kafka-api-secret"
    topics:
      orders: "orders-stream"
      inventory: "inventory-stream"

targets:
  schemas:
    bronze: "bronze"
    silver: "silver"
    gold: "gold"

expectations:
  stores:
    valid_store_id: "store_id IS NOT NULL"
  products:
    valid_product_id: "product_id IS NOT NULL"
    valid_price: "product_retail_price > 0"
  orders:
    valid_quantity: "quantity > 0"
    valid_customer_id: "customer_id IS NOT NULL"